[bell]
duration = 0

[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.cursor]
cursor = "#839496"
text = "#002b36"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#002b36"
foreground = "#839496"

# [colors.bright]
# black = "#002b36"
# blue = "#839496"
# cyan = "#93a1a1"
# green = "#586e75"
# magenta = "#6c71c4"
# red = "#cb4b16"
# white = "#fdf6e3"
# yellow = "#657b83"
#
# [colors.cursor]
# cursor = "#657b83"
# text = "#fdf6e3"
#
# [colors.normal]
# black = "#073642"
# blue = "#268bd2"
# cyan = "#2aa198"
# green = "#859900"
# magenta = "#d33682"
# red = "#dc322f"
# white = "#eee8d5"
# yellow = "#b58900"
#
# [colors.primary]
# background = "#fdf6e3"
# foreground = "#657b83"

[font]
size = 10.0

[font.bold]
family = "Monaco"
style = "Regular"

[font.italic]
family = "Monaco"

[font.normal]
family = "Monaco"

[font.offset]
x = 0
y = -2

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"
mods = "Control"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mode = "~Vi"
mouse = "Middle"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
dynamic_padding = true
startup_mode = "Maximized"

[window.class]
general = "Alacritty"
instance = "Alacritty"
